version: "3.9"
services:
  e2e-screenshot-viewer:
    image: melnikaite/e2e-screenshot-viewer
    container_name: e2e-screenshot-viewer
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - MINIO_ENDPOINT=host.docker.internal
    depends_on:
      - minio

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9500:9000"
      - "9501:9001"
    env_file:
      - .env
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
    driver: local
